### ISSUE TITLE
Runway Site seems to be down

### ISSUE THREAD

**Issue by doctordaveerickson** [epranka/runway-app#3]
https://runway.airportdb.io/ seems to be non-functional.   No matter what ICAO you search, it isn't able to find anything currently.   The api backend to airportdb.io works fine when I try querying via API to it directly.

![image](https://user-images.githubusercontent.com/53024655/152723719-bf9ceb43-ac7f-40ae-b956-bf8f880487f4.png)

**Comment by epranka** [comment]
Thanks for reporting! Will look

**Comment by epranka** [comment]
Looks like it reaches the API rate. I will increase

**Comment by epranka** [comment]
Should be up!
